repos:
  - repo: local
    hooks:
      - id: ruff-check
        name: ruff check
        entry: uv run --directory backend ruff check .
        language: system
        pass_filenames: false
      - id: ruff-format-check
        name: ruff format check
        entry: uv run --directory backend ruff format --check .
        language: system
        pass_filenames: false
      - id: mypy
        name: mypy
        entry: uv run --directory backend mypy boxbase/
        language: system
        pass_filenames: false
